name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 7.4, 8.0 ]
        laravel: [ ^8.0 ]
    name: P${{ matrix.php }} - L${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        run: composer require "illuminate/support=${{ matrix.laravel }}" --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml
        env:
          BILLINGO_API_KEY: ${{ secrets.BILLINGO_API_KEY }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-laravel-billingo
